services:
    postgres:
        image: postgres:17
        container_name: course-db
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres -d courses" ]
            interval: 5s
            timeout: 5s
            retries: 5

    rabbitmq:
        image: rabbitmq:3.13-management
        container_name: course-rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

    api:
        build: .
        container_name: course-api
        ports:
            - "8080:8080"
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
            - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
            - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
            - SPRING_RABBITMQ_HOST=${RABBITMQ_HOST}
            - SPRING_RABBITMQ_PORT=${RABBITMQ_PORT}
            - SPRING_RABBITMQ_USERNAME=${RABBITMQ_USER}
            - SPRING_RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
        depends_on:
            postgres:
                condition: service_healthy
            rabbitmq:
                condition: service_started

volumes:
    postgres_data:
