spring:
    application:
        name: online-course-system
    datasource:
        url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/courses}
        username: ${SPRING_DATASOURCE_USERNAME:postgres}
        password: ${SPRING_DATASOURCE_PASSWORD:postgres}

    jpa:
        hibernate:
            ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
jwt:
    secret: ${JWT_SECRET:363aaf3fa83493353483cab70d0e9af39b4da0cfa12620b742d8a3c315792a73 }
    expiration: 86400000 # 24h
